# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    session:
            handler_id: 'session.handler.native_file' # Gère les sessions avec Symfony
            save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%' # Emplacement pour les sessions
            # improves the security of the cookies used for sessions
            cookie_secure: auto
            cookie_samesite: lax
            storage_factory_id: session.storage.factory.native
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true

    # Note that the session will be started ONLY if you read or write from it.
    # session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
